salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/OSFMX_ConsumosSector__c.object-meta.xml
<CustomObject>
    <description>Tabla de consumos de sector</description>
    <label>OSFMX_ConsumosSector</label>
    <nameField>
        <label>OSFMX_ConsumosSector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OSFMX_ConsumosSectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/Desviacion_Estandar_por_Sector__c.field-meta.xml
<CustomField>
    <fullName>Desviacion_Estandar_por_Sector__c</fullName>
    <label>Desviacion Estandar por Sector</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M10__c.field-meta.xml
<CustomField>
    <fullName>M10__c</fullName>
    <label>M10</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M11__c.field-meta.xml
<CustomField>
    <fullName>M11__c</fullName>
    <label>M11</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M12__c.field-meta.xml
<CustomField>
    <fullName>M12__c</fullName>
    <label>M12</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M1__c.field-meta.xml
<CustomField>
    <fullName>M1__c</fullName>
    <label>M1</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M2__c.field-meta.xml
<CustomField>
    <fullName>M2__c</fullName>
    <label>M2</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M3__c.field-meta.xml
<CustomField>
    <fullName>M3__c</fullName>
    <label>M3</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M4__c.field-meta.xml
<CustomField>
    <fullName>M4__c</fullName>
    <label>M4</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M5__c.field-meta.xml
<CustomField>
    <fullName>M5__c</fullName>
    <label>M5</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M6__c.field-meta.xml
<CustomField>
    <fullName>M6__c</fullName>
    <label>M6</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M7__c.field-meta.xml
<CustomField>
    <fullName>M7__c</fullName>
    <label>M7</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M8__c.field-meta.xml
<CustomField>
    <fullName>M8__c</fullName>
    <label>M8</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M9__c.field-meta.xml
<CustomField>
    <fullName>M9__c</fullName>
    <label>M9</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/Porcentaje_Volatibilidad__c.field-meta.xml
<CustomField>
    <fullName>Porcentaje_Volatibilidad__c</fullName>
    <label>Porcentaje Volatibilidad</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/Volatibilidad__c.field-meta.xml
<CustomField>
    <fullName>Volatibilidad__c</fullName>
    <label>Volatilidad</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/OSMX_Consumos_Clientes__c.object-meta.xml
<CustomObject>
    <label>OSMX_Consumos_Clientes</label>
    <nameField>
        <label>OSMX_Consumos_Clientes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OSMX_Consumos_Clientes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/ID_Instalacion__c.field-meta.xml
<CustomField>
    <fullName>ID_Instalacion__c</fullName>
    <label>ID_Instalacion</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M10__c.field-meta.xml
<CustomField>
    <fullName>M10__c</fullName>
    <label>M10</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M11__c.field-meta.xml
<CustomField>
    <fullName>M11__c</fullName>
    <label>M11</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M12__c.field-meta.xml
<CustomField>
    <fullName>M12__c</fullName>
    <label>M12</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M1__c.field-meta.xml
<CustomField>
    <fullName>M1__c</fullName>
    <label>M1</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M2__c.field-meta.xml
<CustomField>
    <fullName>M2__c</fullName>
    <label>M2</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M3__c.field-meta.xml
<CustomField>
    <fullName>M3__c</fullName>
    <label>M3</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M4__c.field-meta.xml
<CustomField>
    <fullName>M4__c</fullName>
    <label>M4</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M5__c.field-meta.xml
<CustomField>
    <fullName>M5__c</fullName>
    <label>M5</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M6__c.field-meta.xml
<CustomField>
    <fullName>M6__c</fullName>
    <label>M6</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M7__c.field-meta.xml
<CustomField>
    <fullName>M7__c</fullName>
    <label>M7</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M8__c.field-meta.xml
<CustomField>
    <fullName>M8__c</fullName>
    <label>M8</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M9__c.field-meta.xml
<CustomField>
    <fullName>M9__c</fullName>
    <label>M9</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/Promedio_por_Sector__c.field-meta.xml
<CustomField>
    <fullName>Promedio_por_Sector__c</fullName>
    <label>Promedio por Sector</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry</valueSetName>
    </valueSet>
</CustomField>

salesforce_sfdx/main/default/globalValueSets/Industry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Automotriz y autopartes</fullName>
    </customValue>
    <customValue>
        <fullName>Bancos e instituciones financieras</fullName>
    </customValue>
    <customValue>
        <fullName>Bienes de consumo</fullName>
    </customValue>
    <customValue>
        <fullName>Cemento</fullName>
    </customValue>
    <customValue>
        <fullName>Centros Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Cerámicos</fullName>
    </customValue>
    <customValue>
        <fullName>Constructora / Ingeniería</fullName>
    </customValue>
    <customValue>
        <fullName>Data Center</fullName>
    </customValue>
    <customValue>
        <fullName>Educación privada</fullName>
    </customValue>
    <customValue>
        <fullName>Educación pública</fullName>
    </customValue>
    <customValue>
        <fullName>Empresas de Telecomunicación</fullName>
    </customValue>
    <customValue>
        <fullName>Entretenimientos</fullName>
    </customValue>
    <customValue>
        <fullName>Generación eléctrica</fullName>
    </customValue>
    <customValue>
        <fullName>Gestión inmobiliaria</fullName>
    </customValue>
    <customValue>
        <fullName>Gobiernos (Defensa, etc.)</fullName>
    </customValue>
    <customValue>
        <fullName>Hoteles</fullName>
    </customValue>
    <customValue>
        <fullName>Materiales y herramientas</fullName>
    </customValue>
    <customValue>
        <fullName>Metalurgia</fullName>
    </customValue>
    <customValue>
        <fullName>Minería</fullName>
    </customValue>
    <customValue>
        <fullName>Municipalidades</fullName>
    </customValue>
    <customValue>
        <fullName>Parques Industriales</fullName>
    </customValue>
    <customValue>
        <fullName>Petróleo y gas</fullName>
    </customValue>
    <customValue>
        <fullName>Planta / Distribución de agua</fullName>
    </customValue>
    <customValue>
        <fullName>Pulpa y papel</fullName>
    </customValue>
    <customValue>
        <fullName>Química farmacéutica</fullName>
    </customValue>
    <customValue>
        <fullName>Química y Petroquímica</fullName>
    </customValue>
    <customValue>
        <fullName>Retail (tiendas, etc.)</fullName>
    </customValue>
    <customValue>
        <fullName>Salud privada</fullName>
    </customValue>
    <customValue>
        <fullName>Salud pública</fullName>
    </customValue>
    <customValue>
        <fullName>Servicios</fullName>
    </customValue>
    <description>Lista Global creada para manejar los sectores</description>
    <masterLabel>Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

salesforce_sfdx/main/default/classes/OSFMX_ConsumosSectorSchedulable.cls
/**
 * @Description        : Interfaz programable que calcula y almacena los valores para "OSFMX_ConsumosSector__c" 
 * 							en base al contenido de "OSMX_Consumos_Clientes__c".
 * @Modification Log   : 
 * Ver       Date            	Author      		    Modification
 * 1.0    	28/04/2021   		Edgar Maldonado     	Initial Version.
 * 1.1    	25/05/2021   		Edgar Maldonado      	Por solicitud en pruebas integrales, 
 * 															Porcentaje_Volatibilidad__c se redondea a 2 enteros y 2 decimales.
 * 1.2    	03/06/2021   		Edgar Maldonado     	Se corrije error "CANNOT_EXECUTE_FLOW_TRIGGER" de ambiente Integra.
 * 1.3		01/09/2021			Edgar Maldonado			Se ajusta para no tomar en cuenta registros con ID_Instalacion__c 
 * 															distinto a null.
**/
global class OSFMX_ConsumosSectorSchedulable implements Schedulable {
    
	global void execute(SchedulableContext ctx) {
        System.debug('##### OSFMX_ConsumosSectorSchedulable - execute() - Context: ' + ctx);
        List<OSFMX_ConsumosSector__c> consumosSectorList = new List<OSFMX_ConsumosSector__c>();
        List<AggregateResult> sumBySectorList = [
            SELECT Sector__c,SUM(M1__c) m1Sum,SUM(M2__c) m2Sum,SUM(M3__c) m3Sum,SUM(M4__c) m4Sum,SUM(M5__c) m5Sum,
            		SUM(M6__c) m6Sum,SUM(M7__c) m7Sum,SUM(M8__c) m8Sum,SUM(M9__c) m9Sum,SUM(M10__c) m10Sum,
            		SUM(M11__c) m11Sum,SUM(M12__c) m12Sum
            FROM OSMX_Consumos_Clientes__c
            WHERE ID_Instalacion__c=null
            GROUP BY Sector__c
        ];
        List<OSFMX_ConsumosSector__c> consumosSectorToDeleteList = [
            SELECT Id
            FROM OSFMX_ConsumosSector__c
        ];
        
        for(AggregateResult resultItem:sumBySectorList){
            System.debug('##### OSFMX_ConsumosSectorSchedulable - execute() - resultItem: ' + resultItem);
            OSFMX_ConsumosSector__c consumosSectorItem = new OSFMX_ConsumosSector__c();
            String volatility;
            
            String sector = (String)resultItem.get('Sector__c');
            List<Double> sumByMonthList = new List<Double>();
            consumosSectorItem.M1__c=(Double)resultItem.get('m1Sum');
            sumByMonthList.add(consumosSectorItem.M1__c);
			consumosSectorItem.M2__c=(Double)resultItem.get('m2Sum');
            sumByMonthList.add(consumosSectorItem.M2__c);
            consumosSectorItem.M3__c=(Double)resultItem.get('m3Sum');
            sumByMonthList.add(consumosSectorItem.M3__c);
            consumosSectorItem.M4__c=(Double)resultItem.get('m4Sum');
            sumByMonthList.add(consumosSectorItem.M4__c);
            consumosSectorItem.M5__c=(Double)resultItem.get('m5Sum');
            sumByMonthList.add(consumosSectorItem.M5__c);
            consumosSectorItem.M6__c=(Double)resultItem.get('m6Sum');
            sumByMonthList.add(consumosSectorItem.M6__c);
            consumosSectorItem.M7__c=(Double)resultItem.get('m7Sum');
            sumByMonthList.add(consumosSectorItem.M7__c);
            consumosSectorItem.M8__c=(Double)resultItem.get('m8Sum');
            sumByMonthList.add(consumosSectorItem.M8__c);
            consumosSectorItem.M9__c=(Double)resultItem.get('m9Sum');
            sumByMonthList.add(consumosSectorItem.M9__c);
            consumosSectorItem.M10__c=(Double)resultItem.get('m10Sum');
            sumByMonthList.add(consumosSectorItem.M10__c);
            consumosSectorItem.M11__c=(Double)resultItem.get('m11Sum');
            sumByMonthList.add(consumosSectorItem.M11__c);
            consumosSectorItem.M12__c=(Double)resultItem.get('m12Sum');
            sumByMonthList.add(consumosSectorItem.M12__c);
			Double average = calculateAverage(sumByMonthList,false);
            Double standardDeviation = calculateStandardDeviation(sumByMonthList, average, false);
            Decimal volatilityPercentage = 0;
            if(average>0){
                volatilityPercentage = standardDeviation/average;
            }
            volatilityPercentage = volatilityPercentage.setScale(4);
            if(volatilityPercentage<=0.1){
                volatility='BAJA';
            }else{
                volatility='ALTA';
            }
            consumosSectorItem.Sector__c = sector;
            consumosSectorItem.Promedio_por_Sector__c = average;
            consumosSectorItem.Desviacion_Estandar_por_Sector__c = standardDeviation;
            consumosSectorItem.Porcentaje_Volatibilidad__c = volatilityPercentage;
            consumosSectorItem.Volatibilidad__c = volatility;
            consumosSectorList.add(consumosSectorItem);
        }
        
        DELETE consumosSectorToDeleteList;
        INSERT consumosSectorList;
        
        System.debug('##### OSFMX_ConsumosSectorSchedulable - execute() - consumosSectorList insertados: ' + consumosSectorList);
	}
    
    private Double calculateAverage(List<Double> numberList, Boolean doZerosCount){
        Integer counter=0;
        Double totalSum=0;
        
        System.debug('##### OSFMX_ConsumosSectorSchedulable - execute() - calculateAverage - numberList: ' + numberList);
        for(Double item:numberList){
            if(item!=null){
                totalSum+=item;
                if(item!=0||doZerosCount){
                    counter++;
                }
            }
        }
        if(counter>0){
            return totalSum/counter;
        }else{
            return 0;
        }
        
    }
    
    private Double calculateStandardDeviation(List<Double> numberList, Double average, Boolean doZerosCount){
        Integer counter=0;
        Double sumOfSquares=0;
        Double divideSumOfSquares=0;
        Double standardDeviation;
        
        for(Double item:numberList){
            if(item!=null){
                if(item!=0||doZerosCount){
                    counter++;
                    Double squareOfDistanceToAvg = (item - average) * (item - average);
                    sumOfSquares+=squareOfDistanceToAvg;
                }
            }
        }
        if(counter>0){
            divideSumOfSquares = sumOfSquares/counter;
        }
        standardDeviation = System.Math.sqrt(divideSumOfSquares);
        
        return standardDeviation;
    }
}