salesforce_sfdx/main/default/objects/OSFMX_URL__c/OSFMX_URL__c.object-meta.xml
<CustomObject>
    <description>Contiene información relacionada a los reportes semanales de gas y electricidad.</description>
    <label>Reporte Semanal</label>
    <nameField>
        <label>Nombre de reporte</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reportes Semanales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_sfdx/main/default/objects/OSFMX_URL__c/fields/OSFMX_URL_PDF__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_URL_PDF__c</fullName>
    <label>URL PDF</label>
    <type>Url</type>
</CustomField>

salesforce_sfdx/main/default/classes/vlcContentDistributionTriggerTest.cls
@isTest
public class vlcContentDistributionTriggerTest {
    
    static testMethod void testSetQuoteLineItemAttributes() {
        ContentVersion contentVersion = new ContentVersion(
            Title          = 'ContentVersionTest',
            PathOnClient   = 'Pic.jpg',
            VersionData    = Blob.valueOf('Test Content'),
            IsMajorVersion = true);
        INSERT contentVersion;
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        System.debug('>>>>>>>>>>>>>>>> testSetQuoteLineItemAttributes - documents: ' + documents);
        OSFMX_URL__c reporte = new OSFMX_URL__c(Name='Prueba');//Reporte Semanal
        INSERT reporte;
        ContentDistribution contDritib = new ContentDistribution(ContentVersionId = contentVersion.Id, Name = 'ContentDistributionTest', 
                                                                RelatedRecordId=reporte.Id);
        INSERT contDritib;
        List<ContentDistribution> distributions = [SELECT Id, Name, DistributionPublicUrl FROM ContentDistribution];
        System.debug('>>>>>>>>>>>>>>>> testSetQuoteLineItemAttributes - distributions: ' + distributions);
        contDritib.Name = 'ContentDistributionTest_MODX';
        Test.StartTest();
        UPDATE contDritib;
        Test.StopTest();
        List<OSFMX_URL__c> documentos = [SELECT Id, OSFMX_URL_PDF__c FROM OSFMX_URL__c];
        System.assertEquals(distributions.get(0).DistributionPublicUrl,
                            documentos.get(0).OSFMX_URL_PDF__c, 'No se copió la URL de descarga del documento.');
    }
    
}