salesforce_sfdx/main/default/objects/OSFMX_URL__c/OSFMX_URL__c.object-meta.xml
<CustomObject>
    <description>Contiene información relacionada a los reportes semanales de gas y electricidad.</description>
    <label>Reporte Semanal</label>
    <nameField>
        <label>Nombre de reporte</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reportes Semanales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_sfdx/main/default/objects/OSFMX_URL__c/fields/OSFMX_URL_PDF__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_URL_PDF__c</fullName>
    <label>URL PDF</label>
    <type>Url</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_URL__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>Enlace directo a los reportes</description>
    <inlineHelpText>URL de reportes semanales para gas y electricidad.</inlineHelpText>
    <label>URL</label>
    <type>Url</type>
</CustomField>

salesforce_sfdx/main/default/classes/OSFMX_ReporteSemanalPDF_tst.cls
@isTest
public class OSFMX_ReporteSemanalPDF_tst {
    @isTest
    static void getUrlTest() {
        OSFMX_URL__c objRecord = new OSFMX_URL__c(Name = 'Name Test', URL__c = 'https://engieclorg--devmexico.my.salesforce.com/sfc/p/#c0000003wiic/a/c0000000A8ad/f8v7NllIspLl96MdgknfX_h1aBkBo6IGyyK2UBPQcEg');
        insert objRecord;
        String urlExpected = objRecord.OSFMX_URL_PDF__c;
        String urlActual = OSFMX_ReporteSemanalPDF_cls.getUrlReporte();
        System.assertEquals(urlExpected, urlActual, 'Error');
    }
}