salesforce_sfdx/main/default/objects/OSFMX_ContractAccountForBilling__c/OSFMX_ContractAccountForBilling__c.object-meta.xml
<CustomObject>
    <description>Almacena temporalmente cabeceras de la consulta de facturación hacía Denodo y Global Hitss, para mostrar en la vista 360. Debe ser borrada cada noche.</description>
    <label>Cuenta Contrato Para Facturacion</label>
    <nameField>
        <label>Business Partner</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas Contrato Para Facturacion</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_sfdx/main/default/objects/OSFMX_ContractAccountForBilling__c/fields/OSFMX_CuentaContrato__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_CuentaContrato__c</fullName>
    <externalId>true</externalId>
    <label>Cuenta Contrato</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce_sfdx/main/default/classes/OSFMX_DeleteInvoiceBatch.cls
/***********************************************************************************
    Developed by:   Roberto Rodriguez Anaya
    Author      :   Roberto Rodriguez Anaya
    Project     :   OSFMX
    Description :   OSFMX_DeleteInvoiceBatch
   ================================================================================
    No.     Date                 Author                    Description      Comment
    1.0     21-Feb-2021          Roberto Rodriguez Anaya   Creation         ........


************************************************************************************/
global class OSFMX_DeleteInvoiceBatch implements Database.Batchable<sObject>, Database.Stateful {
// instance member to retain state across transactions
    global Integer recordsProcessed = 0;
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        DateTime fecha = system.now();
        System.debug('##### OSFMX_DeleteInvoiceBatch - start() - Fecha: ' + fecha);
        return Database.getQueryLocator(
            [
                SELECT Id,OSFMX_CuentaContrato__c
                FROM OSFMX_ContractAccountForBilling__c
            ]
        );
    }
    
    global void execute(Database.BatchableContext bc, List<OSFMX_ContractAccountForBilling__c> records){
        System.debug('##### OSFMX_DeleteInvoiceBatch - execute - INICIO');
        recordsProcessed+=records.size();
        DELETE records;
    }
    
    global void finish(Database.BatchableContext bc){
        System.debug('##### OSFMX_DeleteInvoiceBatch - finish() - Se actualizaron ' + recordsProcessed + ' registros.');
    }
}