salesforce_sfdx/main/default/objects/OSFMX_Subscription__c/OSFMX_Subscription__c.object-meta.xml
<CustomObject>
    <description>Represents the registry for users subscribed to the report</description>
    <label>Suscripción a Reporte</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Consecutivo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suscripción a Reportes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_sfdx/main/default/objects/OSFMX_Subscription__c/fields/OSFMX_ReportWeekly__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_ReportWeekly__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporte Semanal</label>
    <referenceTo>OSFMX_URL__c</referenceTo>
    <relationshipLabel>Suscripción a Reportes</relationshipLabel>
    <relationshipName>Suscripciones</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_Subscription__c/fields/OSFMX_Subscription__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_Subscription__c</fullName>
    <description>Indicador de Suscripción al reporte</description>
    <label>Suscribirme</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_Subscription__c/fields/OSFMX_SubscriptionEmail__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_SubscriptionEmail__c</fullName>
    <description>Correo del Suscriptor</description>
    <label>Correo Electrónico</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_URL__c/OSFMX_URL__c.object-meta.xml
<CustomObject>
    <description>Contiene información relacionada a los reportes semanales de gas y electricidad.</description>
    <label>Reporte Semanal</label>
    <nameField>
        <label>Nombre de reporte</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reportes Semanales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_sfdx/main/default/classes/OSFMX_UpdateURLSubscriptionBatchTest.cls
/**
 * @Description        : Prueba unitaria de la clase "OSFMX_UpdateURLSubscriptionBatch".
 * @Modification Log   : 
 * Ver       Date            	Author      		    Modification
 * 1.0    02/07/2021   		Edgar Maldonado     	Initial Version.
**/
@isTest
public class OSFMX_UpdateURLSubscriptionBatchTest {
	static testmethod void testExecuteBatch() {
        OSFMX_URL__c documentUrl = new OSFMX_URL__c(Name='OSFMX_UpdateURLSubscriptionBatchTest');
        INSERT documentUrl;
        OSFMX_Subscription__c subscription = new OSFMX_Subscription__c(OSFMX_SubscriptionEmail__c='test@mail.com',OSFMX_Subscription__c='SI');
        INSERT subscription;
        
        Test.startTest();
        OSFMX_UpdateURLSubscriptionBatch myBatchObject = new OSFMX_UpdateURLSubscriptionBatch(documentUrl.Id); 
       	Id batchId = Database.executeBatch(myBatchObject);
        Test.stopTest();
        
        // check that the scheduled job has executed
        List<OSFMX_Subscription__c> quoteList3 = new List<OSFMX_Subscription__c>(
            [
                SELECT Id,Name,OSFMX_ReportWeekly__c
                FROM OSFMX_Subscription__c
            ]
        );
        System.assertEquals(documentUrl.Id, 
                            quoteList3.get(0).OSFMX_ReportWeekly__c,
                            'Los registros de OSFMX_Subscription__c no fueron actualizados.');
    }
}