salesforce_sfdx/main/default/objects/Account/fields/OSFMX_AccountContractID__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_AccountContractID__c</fullName>
    <label>Id Cuenta SAP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/Account/fields/OSFMX_RFC__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_RFC__c</fullName>
    <inlineHelpText>AAA = Siglas del contribuyente;
aammdd = Fecha Creación Entidad (año,
mes, día);
HH = Homonimia, alfanumérico;
D = Dígito verificador, alfanumérico.</inlineHelpText>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/OSFMX_ConsumosSector__c.object-meta.xml
<CustomObject>
    <description>Tabla de consumos de sector</description>
    <label>OSFMX_ConsumosSector</label>
    <nameField>
        <label>OSFMX_ConsumosSector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OSFMX_ConsumosSectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M10__c.field-meta.xml
<CustomField>
    <fullName>M10__c</fullName>
    <label>M10</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M11__c.field-meta.xml
<CustomField>
    <fullName>M11__c</fullName>
    <label>M11</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M12__c.field-meta.xml
<CustomField>
    <fullName>M12__c</fullName>
    <label>M12</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M1__c.field-meta.xml
<CustomField>
    <fullName>M1__c</fullName>
    <label>M1</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M2__c.field-meta.xml
<CustomField>
    <fullName>M2__c</fullName>
    <label>M2</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M3__c.field-meta.xml
<CustomField>
    <fullName>M3__c</fullName>
    <label>M3</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M4__c.field-meta.xml
<CustomField>
    <fullName>M4__c</fullName>
    <label>M4</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M5__c.field-meta.xml
<CustomField>
    <fullName>M5__c</fullName>
    <label>M5</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M6__c.field-meta.xml
<CustomField>
    <fullName>M6__c</fullName>
    <label>M6</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M7__c.field-meta.xml
<CustomField>
    <fullName>M7__c</fullName>
    <label>M7</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M8__c.field-meta.xml
<CustomField>
    <fullName>M8__c</fullName>
    <label>M8</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/M9__c.field-meta.xml
<CustomField>
    <fullName>M9__c</fullName>
    <label>M9</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ConsumosSector__c/fields/Volatibilidad__c.field-meta.xml
<CustomField>
    <fullName>Volatibilidad__c</fullName>
    <label>Volatilidad</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/OSMX_Consumos_Clientes__c.object-meta.xml
<CustomObject>
    <label>OSMX_Consumos_Clientes</label>
    <nameField>
        <label>OSMX_Consumos_Clientes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OSMX_Consumos_Clientes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/Id_Business_Partner__c.field-meta.xml
<CustomField>
    <fullName>Id_Business_Partner__c</fullName>
    <description>Identificador único de business partner en SAP.</description>
    <externalId>true</externalId>
    <label>Id Business Partner</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/ID_Instalacion__c.field-meta.xml
<CustomField>
    <fullName>ID_Instalacion__c</fullName>
    <label>ID_Instalacion</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M10__c.field-meta.xml
<CustomField>
    <fullName>M10__c</fullName>
    <label>M10</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M11__c.field-meta.xml
<CustomField>
    <fullName>M11__c</fullName>
    <label>M11</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M12__c.field-meta.xml
<CustomField>
    <fullName>M12__c</fullName>
    <label>M12</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M1__c.field-meta.xml
<CustomField>
    <fullName>M1__c</fullName>
    <label>M1</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M2__c.field-meta.xml
<CustomField>
    <fullName>M2__c</fullName>
    <label>M2</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M3__c.field-meta.xml
<CustomField>
    <fullName>M3__c</fullName>
    <label>M3</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M4__c.field-meta.xml
<CustomField>
    <fullName>M4__c</fullName>
    <label>M4</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M5__c.field-meta.xml
<CustomField>
    <fullName>M5__c</fullName>
    <label>M5</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M6__c.field-meta.xml
<CustomField>
    <fullName>M6__c</fullName>
    <label>M6</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M7__c.field-meta.xml
<CustomField>
    <fullName>M7__c</fullName>
    <label>M7</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M8__c.field-meta.xml
<CustomField>
    <fullName>M8__c</fullName>
    <label>M8</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/M9__c.field-meta.xml
<CustomField>
    <fullName>M9__c</fullName>
    <label>M9</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/Razon_Social__c.field-meta.xml
<CustomField>
    <fullName>Razon_Social__c</fullName>
    <externalId>true</externalId>
    <label>Razon_Social</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSMX_Consumos_Clientes__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Industry</valueSetName>
    </valueSet>
</CustomField>

salesforce_sfdx/main/default/globalValueSets/Industry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Automotriz y autopartes</fullName>
    </customValue>
    <customValue>
        <fullName>Bancos e instituciones financieras</fullName>
    </customValue>
    <customValue>
        <fullName>Bienes de consumo</fullName>
    </customValue>
    <customValue>
        <fullName>Cemento</fullName>
    </customValue>
    <customValue>
        <fullName>Centros Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Cerámicos</fullName>
    </customValue>
    <customValue>
        <fullName>Constructora / Ingeniería</fullName>
    </customValue>
    <customValue>
        <fullName>Data Center</fullName>
    </customValue>
    <customValue>
        <fullName>Educación privada</fullName>
    </customValue>
    <customValue>
        <fullName>Educación pública</fullName>
    </customValue>
    <customValue>
        <fullName>Empresas de Telecomunicación</fullName>
    </customValue>
    <customValue>
        <fullName>Entretenimientos</fullName>
    </customValue>
    <customValue>
        <fullName>Generación eléctrica</fullName>
    </customValue>
    <customValue>
        <fullName>Gestión inmobiliaria</fullName>
    </customValue>
    <customValue>
        <fullName>Gobiernos (Defensa, etc.)</fullName>
    </customValue>
    <customValue>
        <fullName>Hoteles</fullName>
    </customValue>
    <customValue>
        <fullName>Materiales y herramientas</fullName>
    </customValue>
    <customValue>
        <fullName>Metalurgia</fullName>
    </customValue>
    <customValue>
        <fullName>Minería</fullName>
    </customValue>
    <customValue>
        <fullName>Municipalidades</fullName>
    </customValue>
    <customValue>
        <fullName>Parques Industriales</fullName>
    </customValue>
    <customValue>
        <fullName>Petróleo y gas</fullName>
    </customValue>
    <customValue>
        <fullName>Planta / Distribución de agua</fullName>
    </customValue>
    <customValue>
        <fullName>Pulpa y papel</fullName>
    </customValue>
    <customValue>
        <fullName>Química farmacéutica</fullName>
    </customValue>
    <customValue>
        <fullName>Química y Petroquímica</fullName>
    </customValue>
    <customValue>
        <fullName>Retail (tiendas, etc.)</fullName>
    </customValue>
    <customValue>
        <fullName>Salud privada</fullName>
    </customValue>
    <customValue>
        <fullName>Salud pública</fullName>
    </customValue>
    <customValue>
        <fullName>Servicios</fullName>
    </customValue>
    <description>Lista Global creada para manejar los sectores</description>
    <masterLabel>Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

salesforce_sfdx/main/default/classes/OSFMX_ConsumosSectorSchedulableTest.cls
/**
 * @Description        : Prueba unitaria de la clase "OSFMX_ConsumosSectorSchedulable".
 * @Modification Log   : 
 * Ver       Date            	Author      		    Modification
 * 1.0    	28/04/2021   		Edgar Maldonado     	Initial Version.
 * 1.1    	03/06/2021   		Edgar Maldonado     	Se corrije error "CANNOT_EXECUTE_FLOW_TRIGGER" de ambiente Integra.
 * 1.2    	10/06/2021   		Edgar Maldonado     	Ajuste por Sector__c obligatorio.
 * 1.3		01/09/2021			Edgar Maldonado			Se ajusta para no tomar en cuenta registros con ID_Instalacion__c 
 * 															distinto a null.
**/
@isTest
public class OSFMX_ConsumosSectorSchedulableTest {
	// Dummy CRON expression: midnight on March 15.
    // Because this is a test, job executes
    // immediately after Test.stopTest().
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    
    static testmethod void testScheduledJob() {
        Account cuenta = new Account(Name='Prueba',Industry='Cemento',OSFMX_AccountContractID__c='1234567890',
                                    BillingStreet='test',BillingPostalCode='test',BillingCity='test',
                                    BillingStateCode='AG',BillingCountryCode='MX',OSFMX_RFC__c='ADM1705112JA');
        INSERT cuenta;
        
        OSMX_Consumos_Clientes__c consumoClientesItem = new OSMX_Consumos_Clientes__c();
        consumoClientesItem.Name = 'UnitTest';
        consumoClientesItem.Sector__c = 'Cemento';
        consumoClientesItem.Razon_Social__c='Data Center';
        consumoClientesItem.Id_Business_Partner__c='1234567890';
        consumoClientesItem.M1__c=1;
        consumoClientesItem.M2__c=2;
        consumoClientesItem.M3__c=3;
        consumoClientesItem.M4__c=4;
        consumoClientesItem.M5__c=5;
        consumoClientesItem.M6__c=6;
        consumoClientesItem.M7__c=7;
        consumoClientesItem.M8__c=8;
        consumoClientesItem.M9__c=9;
        consumoClientesItem.M10__c=10;
        consumoClientesItem.M11__c=11;
        consumoClientesItem.M12__c=12;
        INSERT consumoClientesItem;
        System.debug('########## OSFMX_ConsumosSectorSchedulableTest - testScheduledJob - consumoClientesItem: ' 
                    + consumoClientesItem);
         
        Test.startTest();
        // Schedule the test job
        String jobId = System.schedule('OSFMX_ConsumosSectorSchedulableTest',
                                       CRON_EXP, 
                                       new OSFMX_ConsumosSectorSchedulable());
        // Stopping the test will run the job synchronously
        Test.stopTest();
        
        // check that the scheduled job has executed
        CronTrigger cron = 
            [
                SELECT Id,CronJobDetail.Name,State,TimesTriggered,NextFireTime 
                FROM CronTrigger
                ORDER BY CreatedDate
                DESC LIMIT 1
            ];
        System.debug('##### OSFMX_ConsumosSectorSchedulableTest - cron: ' + cron);
        System.assertEquals('OSFMX_ConsumosSectorSchedulableTest', 
                            cron.CronJobDetail.Name, 
                            'La clase Apex no fué programada correctamente.');
        List<OSFMX_ConsumosSector__c> consumosSectorList = [
                SELECT Id,Sector__c,Volatibilidad__c 
                FROM OSFMX_ConsumosSector__c
            ];
        System.debug('########## OSFMX_ConsumosSectorSchedulableTest - testScheduledJob - consumosSectorList: ' 
                    + consumosSectorList);
        System.assertEquals(1, 
                            consumosSectorList.size(),
                            'No se generó el registro correspondiente en OSFMX_ConsumosSector__c.');
    }
}