salesforce_sfdx/main/default/objects/Account/fields/OSFMX_RFC__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_RFC__c</fullName>
    <inlineHelpText>AAA = Siglas del contribuyente;
aammdd = Fecha Creación Entidad (año,
mes, día);
HH = Homonimia, alfanumérico;
D = Dígito verificador, alfanumérico.</inlineHelpText>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_ActualPrice__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_ActualPrice__c</fullName>
    <label>Precio Actual</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_DistributorOrCarrier__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_DistributorOrCarrier__c</fullName>
    <label>Distribuidor/Transportista</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OSFMX_ConnectionPipeline__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Distribución CMG</fullName>
            </value>
            <value>
                <fullName>Distribución NGM</fullName>
            </value>
            <value>
                <fullName>Distribución TMG</fullName>
            </value>
            <value>
                <fullName>Distribución DGJ</fullName>
            </value>
            <value>
                <fullName>Distribución DGQ</fullName>
            </value>
            <value>
                <fullName>Distribución GNP</fullName>
            </value>
            <value>
                <fullName>DGJ-Bajio</fullName>
            </value>
            <value>
                <fullName>Distribución Naturgy Bajio</fullName>
                <label>Naturgy Bajio</label>
            </value>
            <value>
                <fullName>Distribución Naturgy Norte</fullName>
                <label>Naturgy Norte</label>
            </value>
            <value>
                <fullName>Distribución Metrogas</fullName>
                <label>Metrogas</label>
            </value>
            <value>
                <fullName>Distribución Naturgy Toluca</fullName>
                <label>Naturgy Toluca</label>
            </value>
            <value>
                <fullName>Distribución Gas Natural del Noroeste</fullName>
            </value>
            <value>
                <fullName>Usos propios</fullName>
            </value>
            <value>
                <fullName>Gas Natural Comprimido</fullName>
            </value>
            <value>
                <fullName>Transporte Mayakan</fullName>
            </value>
            <value>
                <fullName>Transporte Cenagas</fullName>
            </value>
            <value>
                <fullName>Autotransporte Marabis</fullName>
            </value>
            <value>
                <fullName>Distribución GNP-Mérida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_GasTransportPrice__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_GasTransportPrice__c</fullName>
    <label>Precio estimado transporte de gas</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_IndexReference__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_IndexReference__c</fullName>
    <label>Indice de referencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HH</fullName>
            </value>
            <value>
                <fullName>HSC</fullName>
            </value>
            <value>
                <fullName>WAHA</fullName>
            </value>
            <value>
                <fullName>San J</fullName>
            </value>
            <value>
                <fullName>VPM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_Margen_comercializacion_usd__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_Margen_comercializacion_usd__c</fullName>
    <label>Margen estimado comercialización usd</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_Margen_estimado_molecula_usd__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_Margen_estimado_molecula_usd__c</fullName>
    <label>Margen estimado molecula usd</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_Master_MargenEstimadoMoleculaUSD__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_Master_MargenEstimadoMoleculaUSD__c</fullName>
    <label>Margen Estimado Molecula USD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_MasterConsumoPlazoSTR__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_MasterConsumoPlazoSTR__c</fullName>
    <label>MasterConsumoPlazoSTR</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_MasterCuadrante__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_MasterCuadrante__c</fullName>
    <label>MasterCuadrante</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_MasterDailyVolume__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_MasterDailyVolume__c</fullName>
    <label>MasterDailyVolume</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_MasterGwhYear__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_MasterGwhYear__c</fullName>
    <label>MasterGwhYear</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_MasterNivelApro__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_MasterNivelApro__c</fullName>
    <label>MasterNivelApro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_OfferType__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_OfferType__c</fullName>
    <label>Tipo de oferta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vinculante</fullName>
            </value>
            <value>
                <fullName>No Vinculante</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_ParticularSpecifications__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_ParticularSpecifications__c</fullName>
    <label>Específicaciones particulares</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cte nuevo,  sin condicion particular</fullName>
                <label>Cliente nuevo,  sin condicion particular</label>
            </value>
            <value>
                <fullName>Cte nuevo,  con condiciones especiales</fullName>
                <label>Cliente nuevo,  con condiciones especiales</label>
            </value>
            <value>
                <fullName>Cliente Existente, sin condición particular</fullName>
                <label>Cliente existente, sin condición particular</label>
            </value>
            <value>
                <fullName>Cliente Existente, con condiciones Especiales</fullName>
                <label>Cliente existente, con condiciones Especiales</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_Plazo_suministro_Gas__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_Plazo_suministro_Gas__c</fullName>
    <label>Plazo de suministro Gas</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_PriceStructure__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_PriceStructure__c</fullName>
    <label>Estructura de precio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>100% Volumétrico</fullName>
            </value>
            <value>
                <fullName>Firme/Interrumpible</fullName>
            </value>
            <value>
                <fullName>Otro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_Rango_comercializaci_n__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_Rango_comercializaci_n__c</fullName>
    <label>Rango comercialización</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_RequestedVolumeGjYear__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_RequestedVolumeGjYear__c</fullName>
    <formula>Opportunity.OSFMX_ExpConsGjByYear__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Volumen Solicitado (Gj/año)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_Spread_BC_excedente_USD_Gj__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_Spread_BC_excedente_USD_Gj__c</fullName>
    <label>Spread BC excedente USD Gj</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_Spread_piso_por_cuadrante__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_Spread_piso_por_cuadrante__c</fullName>
    <label>Spread piso por cuadrante</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMXSpreadAvoidCurrenSymbol__c.field-meta.xml
<CustomField>
    <fullName>OSFMXSpreadAvoidCurrenSymbol__c</fullName>
    <formula>OSFMX_Spread_ofertado_USD_Gj__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Spread ofertado Avoid Curren Symbol</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSMXConsumo_Plazo__c.field-meta.xml
<CustomField>
    <fullName>OSMXConsumo_Plazo__c</fullName>
    <formula>OSFMX_GJ__c*(OSFMX_Plazo_suministro_Gas__c/12)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Consumo Plazo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/classes/OSFMX_MultiSiteComponentCtrl.cls
public with sharing class OSFMX_MultiSiteComponentCtrl {
    public Id masterQuoteId{get;set;}
    public String titleMaster{get;set;}
    public String detailMaster{get;set;}
    public List<String> titleChild{get;set;}
    public List<String> detailChild{get;set;}      
    public List<Quote> childQuotes;
    public Quote quote;
    
    
    public OSFMX_MultiSiteComponentCtrl() {
        titleMaster = '#009BFF';
        detailMaster = '#80CDFF';
        titleChild = new List<String>();
        detailChild = new List<String>();  
        titleChild.add('#A4A4A4');
        titleChild.add('#72C660');
        detailChild.add('#CFCFCF');
        detailChild.add('#A6CA9E');
                            
    }
    public Quote getQuote(){
        quote = [SELECT Id,Account.Name,Account.OSFMX_RFC__c,OSFMX_MasterNivelApro__c,OSFMX_OfferType__c,OSFMX_Plazo_suministro_Gas__c,
        OSFMX_RequestedVolumeGjYear__c,OSFMX_MasterDailyVolume__c,OSFMX_MasterGwhYear__c,OSFMX_MasterConsumoPlazoSTR__c,OSFMX_IndexReference__c,
        OSFMX_MasterCuadrante__c,OSFMX_Master_MargenEstimadoMoleculaUSD__c,OSFMX_Rango_comercializaci_n__c,OSFMX_Margen_comercializacion_usd__c
         FROM Quote WHERE Id =:masterQuoteId limit 1];
        return quote;
    }
    public List<Quote> getChildQuotes(){
        childQuotes = [SELECT Id, Name,OSMXConsumo_Plazo__c, OSFMX_ParticularSpecifications__c, OSFMX_DistributorOrCarrier__c, OSFMX_ActualPrice__c, 
        OSFMX_PriceStructure__c, OSFMX_Spread_piso_por_cuadrante__c, OSFMX_Margen_estimado_molecula_usd__c, OSFMX_GasTransportPrice__c, 
        OSFMXSpreadAvoidCurrenSymbol__c, OSFMX_Spread_BC_excedente_USD_Gj__c,vlocity_cmt__DefaultServicePointId__r.Name,OSFMX_IndexReference__c
        FROM Quote WHERE vlocity_cmt__ParentQuoteId__c =:masterQuoteId];
        return childQuotes;
    }

    /*public List<Quote> getchildQuotes(){
        return childQuotes;
    }
    public String gettitleMaster(){
        return titleMaster;
    }
    public Quote getquote(){
        return quote;
    }
    public String getdetailMaster(){
        return detailMaster;
    }
    public List<String> gettitleChild(){
        return titleChild;
    }
    public List<String> getdetailChild(){
        return detailChild;
    }*/
}