salesforce_sfdx/main/default/objects/Quote/fields/Cargo_por_Capacidad__c.field-meta.xml
<CustomField>
    <fullName>Cargo_por_Capacidad__c</fullName>
    <label>Cargo por Capacidad</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/Cargo_por_Servicio__c.field-meta.xml
<CustomField>
    <fullName>Cargo_por_Servicio__c</fullName>
    <label>Cargo por Servicio</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/Cargo_por_Uso__c.field-meta.xml
<CustomField>
    <fullName>Cargo_por_Uso__c</fullName>
    <label>Cargo por Uso</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/Cargo_Volumetrico__c.field-meta.xml
<CustomField>
    <fullName>Cargo_Volumetrico__c</fullName>
    <label>Cargo Volumétrico</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/Clasificacion_Tarifaria__c.field-meta.xml
<CustomField>
    <fullName>Clasificacion_Tarifaria__c</fullName>
    <label>Clasificacion Tarifaria</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_Amount__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_Amount__c</fullName>
    <label>Importe</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_CostNoStandardConnection__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_CostNoStandardConnection__c</fullName>
    <label>Costo de conexión no estandar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_CostStandardConnection__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_CostStandardConnection__c</fullName>
    <label>Costo de conexión estandar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_DistributorOrCarrier__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_DistributorOrCarrier__c</fullName>
    <label>Distribuidor/Transportista</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OSFMX_ConnectionPipeline__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Distribución CMG</fullName>
            </value>
            <value>
                <fullName>Distribución NGM</fullName>
            </value>
            <value>
                <fullName>Distribución TMG</fullName>
            </value>
            <value>
                <fullName>Distribución DGJ</fullName>
            </value>
            <value>
                <fullName>Distribución DGQ</fullName>
            </value>
            <value>
                <fullName>Distribución GNP</fullName>
            </value>
            <value>
                <fullName>DGJ-Bajio</fullName>
            </value>
            <value>
                <fullName>Distribución Naturgy Bajio</fullName>
                <label>Naturgy Bajio</label>
            </value>
            <value>
                <fullName>Distribución Naturgy Norte</fullName>
                <label>Naturgy Norte</label>
            </value>
            <value>
                <fullName>Distribución Metrogas</fullName>
                <label>Metrogas</label>
            </value>
            <value>
                <fullName>Distribución Naturgy Toluca</fullName>
                <label>Naturgy Toluca</label>
            </value>
            <value>
                <fullName>Distribución Gas Natural del Noroeste</fullName>
            </value>
            <value>
                <fullName>Usos propios</fullName>
            </value>
            <value>
                <fullName>Gas Natural Comprimido</fullName>
            </value>
            <value>
                <fullName>Transporte Mayakan</fullName>
            </value>
            <value>
                <fullName>Transporte Cenagas</fullName>
            </value>
            <value>
                <fullName>Autotransporte Marabis</fullName>
            </value>
            <value>
                <fullName>Distribución GNP-Mérida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_GasTransportPrice__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_GasTransportPrice__c</fullName>
    <label>Precio estimado transporte de gas</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_GJ__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_GJ__c</fullName>
    <label>Consumo en Gj /año</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_IndexReference__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_IndexReference__c</fullName>
    <label>Indice de referencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HH</fullName>
            </value>
            <value>
                <fullName>HSC</fullName>
            </value>
            <value>
                <fullName>WAHA</fullName>
            </value>
            <value>
                <fullName>San J</fullName>
            </value>
            <value>
                <fullName>VPM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_MeterNotStandarConnection__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_MeterNotStandarConnection__c</fullName>
    <label>Metros de Conexión No Estándar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_Monto_Rango_Monto__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_Monto_Rango_Monto__c</fullName>
    <label>Monto Rango Monto</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_Quadrant__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_Quadrant__c</fullName>
    <label>Cuadrante</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_Rango_comercializaci_n__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_Rango_comercializaci_n__c</fullName>
    <label>Rango comercialización</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_Solution__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_Solution__c</fullName>
    <label>Solución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All in: Compresión, transporte y descompresión</fullName>
            </value>
            <value>
                <fullName>Auditoría de Eficiencia Energética</fullName>
            </value>
            <value>
                <fullName>Cogeneración (on site)</fullName>
            </value>
            <value>
                <fullName>Comercialización + Conducción</fullName>
            </value>
            <value>
                <fullName>Comercialización a través de un tercero</fullName>
            </value>
            <value>
                <fullName>Compresión molécula</fullName>
            </value>
            <value>
                <fullName>Conducción</fullName>
            </value>
            <value>
                <fullName>Conexiones Gas Natural</fullName>
            </value>
            <value>
                <fullName>Corporate PPA Renovable</fullName>
            </value>
            <value>
                <fullName>Corporate PPA Térmico</fullName>
            </value>
            <value>
                <fullName>Distribución + Comercialización</fullName>
            </value>
            <value>
                <fullName>Distribución Simple</fullName>
            </value>
            <value>
                <fullName>Ducto Dedicado</fullName>
            </value>
            <value>
                <fullName>ESCO</fullName>
            </value>
            <value>
                <fullName>EV Chargers</fullName>
            </value>
            <value>
                <fullName>EV Chargers + Flotas</fullName>
            </value>
            <value>
                <fullName>Excedentes</fullName>
            </value>
            <value>
                <fullName>Flotas de Vehículos Eléctricos</fullName>
            </value>
            <value>
                <fullName>Flotas de Vehículos GNV</fullName>
            </value>
            <value>
                <fullName>Hard Facility Management</fullName>
            </value>
            <value>
                <fullName>HVAC Retrofit</fullName>
            </value>
            <value>
                <fullName>Instalación estación GNV onsite</fullName>
            </value>
            <value>
                <fullName>Integrated Facility Management</fullName>
            </value>
            <value>
                <fullName>MEM</fullName>
            </value>
            <value>
                <fullName>Molécula pura</fullName>
            </value>
            <value>
                <fullName>O&amp;M Industrial</fullName>
            </value>
            <value>
                <fullName>O&amp;M Plantas Fotovoltaicas</fullName>
            </value>
            <value>
                <fullName>PPA Renovable</fullName>
            </value>
            <value>
                <fullName>PPA Térmico</fullName>
            </value>
            <value>
                <fullName>Rooftop PV (on site)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_Spread_ofertado_USD_Gj__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_Spread_ofertado_USD_Gj__c</fullName>
    <label>Spread ofertado (USD/Gj)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_TimeLimitSupply__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_TimeLimitSupply__c</fullName>
    <label>Plazo de suministro</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMXGarantiaMoleculaTrans__c.field-meta.xml
<CustomField>
    <fullName>OSFMXGarantiaMoleculaTrans__c</fullName>
    <formula>OSMXConsumo_Plazo__c*(Garantia_Costo_Molecula_estimado__c + IF (ISBLANK(OSFMX_GasTransportPrice__c), 0,OSFMX_GasTransportPrice__c))</formula>
    <label>GarantiaMoleculaTrans</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMXUsoCapacidad__c.field-meta.xml
<CustomField>
    <fullName>OSFMXUsoCapacidad__c</fullName>
    <formula>(OSFMX_TimeLimitSupply__c/12)*(OSFMX_Maximumdailycapacity__c*365)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UsoCapacidad</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSMXConsumo_Plazo__c.field-meta.xml
<CustomField>
    <fullName>OSMXConsumo_Plazo__c</fullName>
    <formula>OSFMX_GJ__c*(OSFMX_Plazo_suministro_Gas__c/12)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Consumo Plazo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/classes/OSFMX_CopyJsonAttributesToQLI.cls
global with sharing class OSFMX_CopyJsonAttributesToQLI implements vlocity_cmt.VlocityOpenInterface {
    
    global Boolean invokeMethod(String methodName, Map<String,Object> input, Map<String,Object> output, Map<String,Object> options) {
    /*Registro valores atributos */
    
        Boolean res = true;
        try {
            if(methodName == 'setQuoteLineItemAttributes') {
                res = setQuoteLineItemAttributes(input, output, options);
            }
        } catch(Exception e) {
            System.debug('::: JSONAttributeFieldService.invokeMethod --> ERROR : ' + e.getMessage() + ' - ' + e.getStackTraceString());
            output.put('EXC',e.getMessage() + ' - ' + e.getStackTraceString());
            throw e;
        }
        return res;
    }
    
    global static Boolean setQuoteLineItemAttributes(Map<String,Object> input, Map<String,Object> output, Map<String,Object> options) {
        String quoteId = (String) options.get('quoteId');
        Boolean checkApproval = (Boolean) options.get('checkApproval');
        //List<String> quoteLineItems = new List<String>();
        System.debug('JSONAttributeFieldService-setQuoteLineItemAttributes: quoteID ' + quoteId);
        
        Decimal valorconexest;
        valorconexest = 1.0;
        
        List<QuoteLineItem> quoteItems = new List<QuoteLineItem>();
        for(QuoteLineItem qli : [SELECT Id, vlocity_cmt__JSONAttribute__c, Product2.vlocity_cmt__JSONAttribute__c, Product2.ProductCode,
                                 Quote.OSFMX_IndexReference__c, Quote.OSFMX_Spread_ofertado_USD_Gj__c, Quote.OSFMX_DistributorOrCarrier__c, 
                                 Quote.OSFMX_Rango_comercializaci_n__c, Quote.Clasificacion_Tarifaria__c, Quote.OSFMX_GJ__c, Quote.Cargo_por_Uso__c, 
                                 Quote.Cargo_por_Capacidad__c, Quote.Cargo_por_Servicio__c, Quote.OSFMX_GasTransportprice__c, Quote.OSFMX_Quadrant__c,
                                 Quote.OSMXConsumo_Plazo__c, Quote.OSFMXGarantiaMoleculaTrans__c, Quote.OSFMX_Solution__c, Quote.OSFMX_TimeLimitSupply__c,
                                 Quote.OSFMXUsoCapacidad__c, Quote.OSFMX_MeterNotStandarConnection__c, Quote.OSFMX_Monto_Rango_Monto__c, Quote.OSFMX_Amount__c,
                                 Quote.Cargo_Volumetrico__c,Quote.OSFMX_CostStandardConnection__c ,Quote.OSFMX_CostNoStandardConnection__c,
                                 vlocity_cmt__UsagePriceTotal__c,vlocity_cmt__EffectiveUsageQuantity__c,vlocity_cmt__UsageQuantity__c,vlocity_cmt__UsageUnitPrice__c
                                 FROM QuoteLineItem WHERE QuoteId =: quoteId]) {
                                     
                                     List<Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest> actionRequestsList = new List<Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest>();
                                     Vlocity_cmt.JSONAttributeSupport jsonSupport = new Vlocity_cmt.JSONAttributeSupport();
                                     
                                     Map<String, object> inputMap = new Map<String, object>{
                                         'objectSO' => null,
                                             'runTimeAttributesJSON'  => qli.vlocity_cmt__JSONAttribute__c,
                                             'originalAttributesJSON' => qli.Product2.vlocity_cmt__JSONAttribute__c
                                             }; 
                                                 Map<String, object> outputMap = new Map<String, object>(); 
                                     Map<String, object> optionsMap = new Map<String, object>();   
                                     
                                     if(qli.Product2.ProductCode == 'ENG_Molecula' ) {
                                         
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_Indice', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSFMX_IndexReference__c));   
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_Cuadrante', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSFMX_Quadrant__c ));
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_Rango_de_Consumo', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSFMX_Monto_Rango_Monto__c ));
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_ConsumoAnualEsperado', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSFMX_GJ__c ));
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_Spread', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSFMX_Spread_ofertado_USD_Gj__c));
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_Distribuidor', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSFMX_DistributorOrCarrier__c ));
                                         qli.vlocity_cmt__UsagePriceTotal__c = qli.Quote.OSFMX_Amount__c;//05/07/2021
                                         
                                         
                                     } else if(qli.Product2.ProductCode == 'ENG_Comercializacion') {
                                         
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_Rango_de_Consumo', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSFMX_Monto_Rango_Monto__c ));
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ATT_EST_USAGE_QTY', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSMXConsumo_Plazo__c));
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_Distribuidor', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSFMX_DistributorOrCarrier__c ));
                                         if(qli.Quote.OSMXConsumo_Plazo__c!=null&&qli.Quote.OSFMX_Monto_Rango_Monto__c!=null){
                                             qli.vlocity_cmt__UsagePriceTotal__c = qli.Quote.OSMXConsumo_Plazo__c * qli.Quote.OSFMX_Monto_Rango_Monto__c;//05/07/2021
                                         }
                                         qli.vlocity_cmt__EffectiveUsageQuantity__c = qli.Quote.OSMXConsumo_Plazo__c;//05/07/2021
                                         qli.vlocity_cmt__UsageQuantity__c = qli.Quote.OSMXConsumo_Plazo__c;//05/07/2021
                                         
                                     } else if(qli.Product2.ProductCode == 'ENG_TransporteTarifa') {
                                         
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ATT_EST_USAGE_QTY', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSFMXGarantiaMoleculaTrans__c ));
                                         qli.vlocity_cmt__UsagePriceTotal__c = qli.Quote.OSFMXGarantiaMoleculaTrans__c;//05/07/2021
                                         qli.vlocity_cmt__EffectiveUsageQuantity__c = qli.Quote.OSFMXGarantiaMoleculaTrans__c;//05/07/2021
                                         qli.vlocity_cmt__UsageQuantity__c = qli.Quote.OSFMXGarantiaMoleculaTrans__c;//05/07/2021
                                         qli.vlocity_cmt__UsageUnitPrice__c = 1;//05/07/2021
                                         
                                     } else if(qli.Product2.ProductCode == 'ENG_Servicio') {
                                         
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ATT_EST_USAGE_QTY', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSFMX_TimeLimitSupply__c ));
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_Distribuidor', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSFMX_DistributorOrCarrier__c ));
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_ClasificacionTarifaria', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.Clasificacion_Tarifaria__c));
                                         if(qli.Quote.OSFMX_TimeLimitSupply__c!=null&&qli.Quote.Cargo_por_Servicio__c!=null){
                                             qli.vlocity_cmt__UsagePriceTotal__c = qli.Quote.OSFMX_TimeLimitSupply__c * qli.Quote.Cargo_por_Servicio__c;//05/07/2021
                                         }
                                         qli.vlocity_cmt__EffectiveUsageQuantity__c = qli.Quote.OSFMX_TimeLimitSupply__c;//05/07/2021
                                         qli.vlocity_cmt__UsageQuantity__c = qli.Quote.OSFMX_TimeLimitSupply__c;//05/07/2021
                                     }
                                     
                                     else if(qli.Product2.ProductCode == 'ENG_Capacidad') {
                                         
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ATT_EST_USAGE_QTY', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSFMXUsoCapacidad__c ));
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_Distribuidor', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSFMX_DistributorOrCarrier__c ));
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_ClasificacionTarifaria', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.Clasificacion_Tarifaria__c));
                                         if(qli.Quote.OSFMXUsoCapacidad__c!=null&&qli.Quote.Cargo_por_Capacidad__c!=null){
                                             qli.vlocity_cmt__UsagePriceTotal__c = qli.Quote.OSFMXUsoCapacidad__c * qli.Quote.Cargo_por_Capacidad__c;//05/07/2021
                                         }
                                         qli.vlocity_cmt__EffectiveUsageQuantity__c = qli.Quote.OSFMXUsoCapacidad__c;//05/07/2021
                                         qli.vlocity_cmt__UsageQuantity__c = qli.Quote.OSFMXUsoCapacidad__c;//05/07/2021
                                     }   
                                     
                                     else if(qli.Product2.ProductCode == 'ENG_Uso') {
                                         
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ATT_EST_USAGE_QTY', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSMXConsumo_Plazo__c ));
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_Distribuidor', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSFMX_DistributorOrCarrier__c ));
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_ClasificacionTarifaria', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.Clasificacion_Tarifaria__c));
                                         if(qli.Quote.OSMXConsumo_Plazo__c!=null&&qli.Quote.Cargo_por_Uso__c!=null){
                                             qli.vlocity_cmt__UsagePriceTotal__c = qli.Quote.OSMXConsumo_Plazo__c * qli.Quote.Cargo_por_Uso__c;//05/07/2021
                                         }
                                         qli.vlocity_cmt__EffectiveUsageQuantity__c = qli.Quote.OSMXConsumo_Plazo__c;//05/07/2021
                                         qli.vlocity_cmt__UsageQuantity__c = qli.Quote.OSMXConsumo_Plazo__c;//05/07/2021
                                     }
                                     
                                     else if(qli.Product2.ProductCode == 'ENG_Volumetria') {
                                         
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ATT_EST_USAGE_QTY', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSMXConsumo_Plazo__c ));
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_Distribuidor', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSFMX_DistributorOrCarrier__c ));
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_ClasificacionTarifaria', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.Clasificacion_Tarifaria__c));
                                         if(qli.Quote.OSMXConsumo_Plazo__c!=null&&qli.Quote.Cargo_Volumetrico__c!=null){
                                             qli.vlocity_cmt__UsagePriceTotal__c = qli.Quote.OSMXConsumo_Plazo__c * qli.Quote.Cargo_Volumetrico__c;//05/07/2021
                                         }
                                         qli.vlocity_cmt__EffectiveUsageQuantity__c = qli.Quote.OSMXConsumo_Plazo__c;//05/07/2021
                                         qli.vlocity_cmt__UsageQuantity__c = qli.Quote.OSMXConsumo_Plazo__c;//05/07/2021
                                     }                         
                                     else if(qli.Product2.ProductCode == 'ENG_Conexion_Estandard') {
                                         
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ATT_EST_USAGE_QTY', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, valorconexest ));
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_Distribuidor', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSFMX_DistributorOrCarrier__c ));
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_ClasificacionTarifaria', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.Clasificacion_Tarifaria__c));
                                         if(valorconexest!=null&&qli.Quote.OSFMX_CostStandardConnection__c!=null){
                                             qli.vlocity_cmt__UsagePriceTotal__c = valorconexest * qli.Quote.OSFMX_CostStandardConnection__c;//05/07/2021
                                         }
                                         qli.vlocity_cmt__EffectiveUsageQuantity__c = valorconexest;//05/07/2021
                                         qli.vlocity_cmt__UsageQuantity__c = valorconexest;//05/07/2021
                                     } 
                                     
                                     else if(qli.Product2.ProductCode == 'ENG_Conexion_NoEstandard') {
                                         
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ATT_EST_USAGE_QTY', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSFMX_MeterNotStandarConnection__c ));
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_Distribuidor', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.OSFMX_DistributorOrCarrier__c ));
                                         actionRequestsList.add(new Vlocity_cmt.JSONAttributeSupport.JSONAttributeActionRequest('ENG_ClasificacionTarifaria', Vlocity_cmt.JSONAttributeSupport.ActionType.ASSIGN, qli.Quote.Clasificacion_Tarifaria__c));
                                         if(qli.Quote.OSFMX_MeterNotStandarConnection__c!=null&&qli.Quote.OSFMX_CostNoStandardConnection__c!=null){
                                             qli.vlocity_cmt__UsagePriceTotal__c = qli.Quote.OSFMX_MeterNotStandarConnection__c * qli.Quote.OSFMX_CostNoStandardConnection__c;//05/07/2021
                                         }
                                         qli.vlocity_cmt__EffectiveUsageQuantity__c = qli.Quote.OSFMX_MeterNotStandarConnection__c;//05/07/2021
                                         qli.vlocity_cmt__UsageQuantity__c = qli.Quote.OSFMX_MeterNotStandarConnection__c;//05/07/2021
                                     }                        
                                     
                                     else {
                                     }                                 
                                     
                                     inputMap.put('JSONAttributeActionRequestList', actionRequestsList);
                                     jsonSupport.invokeMethod('applyAttributeActions', inputMap, outputMap, optionsMap); 
                                     
                                     String modifiedJSON = (String)outputMap.get('modifiedJSON');
                                     System.debug('JSONAttributeFieldService-setQuoteLineItemAttributes: modifiedJSON : ' + modifiedJSON);
                                     
                                     qli.vlocity_cmt__JSONAttribute__c = modifiedJSON;
                                     quoteItems.add(qli);
                                     //quoteLineItems.add(qli.Id);
                                     System.debug('JSONAttributeFieldService-setQuoteLineItemAttributes-QLI(Id,UsagePriceTotal,' 
                                                  + 'EffectiveUsageQuantity,UsageQuantity,UsageUnitPrice): (' 
                                                  + qli.Id + ',' + qli.vlocity_cmt__UsagePriceTotal__c + ','
                                                  + qli.vlocity_cmt__EffectiveUsageQuantity__c + ','
                                                  + qli.vlocity_cmt__UsageQuantity__c + ','
                                                  + qli.vlocity_cmt__UsageUnitPrice__c + ')'
                                                 );//05/07/2021
                                 }
        
        if(!quoteItems.isEmpty()) {
            update quoteItems;
            System.debug('JSONAttributeFieldService-setQuoteLineItemAttributes- quoteItems actualizados: ' + quoteItems);
        }
        
        updateProducts(quoteId,checkApproval);
        return false;
    }
    
    @future(callout=true)
    private static void updateProducts(String quoteId, Boolean checkApproval) {
        Map<String,Object> inpIP = new Map<String,Object>{'ContextId' => quoteId,'checkApproval'=>checkApproval};
            Map<String,Object> optIP = new Map<String,Object>();
        vlocity_cmt.IntegrationProcedureService.runIntegrationService('OSFMX_GetCartItems', inpIP, optIP);
        
        System.debug('--> optIP' + optIP);
    }
    
}