salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_OppServicePointType__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_OppServicePointType__c</fullName>
    <description>Muestra si la oportunidad/oferta es punto o multipunto</description>
    <label>Tipo de Oportunidad</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Un punto</fullName>
            </value>
            <value>
                <fullName>Multipunto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_SolutionType__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_SolutionType__c</fullName>
    <label>Tipo de solución</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Comercialización de Gas Natural</fullName>
            </value>
            <value>
                <fullName>Corporate PPA</fullName>
            </value>
            <value>
                <fullName>MexCom</fullName>
            </value>
            <value>
                <fullName>Distribución de Gas Natural</fullName>
            </value>
            <value>
                <fullName>Ducto Dedicado</fullName>
            </value>
            <value>
                <fullName>Eficiencia Energética</fullName>
            </value>
            <value>
                <fullName>Generación Onsite</fullName>
            </value>
            <value>
                <fullName>GNC</fullName>
            </value>
            <value>
                <fullName>GNV</fullName>
            </value>
            <value>
                <fullName>Instalación</fullName>
            </value>
            <value>
                <fullName>Mantenimiento</fullName>
            </value>
            <value>
                <fullName>Movilidad Eléctrica</fullName>
            </value>
            <value>
                <fullName>Suministro Eléctrico MX</fullName>
            </value>
            <value>
                <fullName>Suministro Eléctrico Latam</fullName>
            </value>
            <value>
                <fullName>Soluciones</fullName>
            </value>
            <value>
                <fullName>Transmisión</fullName>
            </value>
            <value>
                <fullName>Gas Chile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce_sfdx/main/default/objects/Quote/fields/OSFMX_SubEstatus__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_SubEstatus__c</fullName>
    <label>Sub estado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Solicitud</fullName>
            </value>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Autorización</fullName>
            </value>
            <value>
                <fullName>Producto (Oferta con observaciones)</fullName>
            </value>
            <value>
                <fullName>Factibilidad Mexcom</fullName>
            </value>
            <value>
                <fullName>Factibilidad eléctrica</fullName>
            </value>
            <value>
                <fullName>Factibilidad distribución</fullName>
            </value>
            <value>
                <fullName>Factibilidad ducto dedicado</fullName>
            </value>
            <value>
                <fullName>Factibilidad otras soluciones</fullName>
            </value>
            <value>
                <fullName>Aprobación</fullName>
            </value>
            <value>
                <fullName>Factibilidad imposible</fullName>
            </value>
            <value>
                <fullName>Producto imposible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce_sfdx/main/default/classes/OSFMX_QuoteTriggerHandler.cls
public with sharing class OSFMX_QuoteTriggerHandler {

    public static void beforeUpdate(Map<Id, Quote> oldQuoteById, List<Quote> newQuotes) {
        List<Quote> listQuotes = new List<Quote>();
        for (Quote oferta : newQuotes) {
            if (oferta.OSFMX_OppServicePointType__c!='Multipunto' && oferta.Status=='Aprobada' && oferta.OSFMX_SolutionType__c=='Distribución de Gas Natural' ){
        		listQuotes.add(oferta);
            }
        }
        if(listQuotes.size()>0){
        	OSFMX_QuoteTriggerHelper.generateQuotePDF(oldQuoteById, listQuotes);
        }
    }

    public static void afterUpdate(Map<Id, Quote> oldQuoteById, List<Quote> newQuotes) {
       	List<Quote> listQuotesUpdateService = new List<Quote>();
        List<Quote> listQuotesCustomNotification = new List<Quote>();
        for (Quote oferta : newQuotes) {
            if (oferta.vlocity_cmt__ParentQuoteId__c!=null && oferta.OSFMX_OppServicePointType__c=='Multipunto' && oferta.Status!='Borrador' ){
                listQuotesUpdateService.add(oferta);
            }
            if (
                (oferta.OSFMX_OppServicePointType__c!='Multipunto' && (oferta.Status=='Aprobada'||(oferta.Status=='Observaciones' && oferta.OSFMX_SubEstatus__c=='Aprobación')))
                ||
               (oferta.vlocity_cmt__ParentQuoteId__c==null && oferta.OSFMX_OppServicePointType__c=='Multipunto' && (oferta.Status=='Aprobada'||(oferta.Status=='Observaciones' && oferta.OSFMX_SubEstatus__c=='Aprobación')))
            ){
                listQuotesCustomNotification.add(oferta);
            }

        }



        if (listQuotesUpdateService.size()>0){
            OSFMX_QuoteTriggerHelper.updateServicePointByOffer(listQuotesUpdateService);
        }
        if (listQuotesCustomNotification.size()>0){
            OSFMX_QuoteTriggerHelper.createCustomNotification(oldQuoteById, listQuotesCustomNotification);
        }
    }

    public static void afterUpdateMaster(Map<Id, Quote> oldQuoteById, List<Quote> newMasterQuote){
        List<Quote> listMasterQuote = new List<Quote>();
        List<Quote> listSendEmail = new List<Quote>();
        for (Quote masterQuote : newMasterQuote){
            Quote oldQuote = oldQuoteById.get(masterQuote.Id);

            if ((masterQuote.Status=='Aprobada'||(masterQuote.Status=='Observaciones' && masterQuote.OSFMX_SubEstatus__c=='Aprobación'))){
                listMasterQuote.add(masterQuote);
            }

        }
        System.debug('listsize::'+listSendEmail.size());
        if (listMasterQuote.size()>0) {
            OSFMX_QuoteTriggerHelper.updateStatusChildQuote(listMasterQuote);
        }
        
    }
}