salesforce_sfdx/main/default/objects/OSFMX_360ViewInvoice__c/OSFMX_360ViewInvoice__c.object-meta.xml
<CustomObject>
    <description>Almacena temporalmente registros de la consulta de facturación hacía Denodo y Global Hitss, para mostrar en la vista 360. Debe ser borrada cada noche.</description>
    <label>Factura Vista 360</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas Vista 360</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce_sfdx/main/default/objects/OSFMX_360ViewInvoice__c/fields/OSFMX_ContractAccountForBilling__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_ContractAccountForBilling__c</fullName>
    <label>Cuenta Contrato Para Facturacion</label>
    <referenceTo>OSFMX_ContractAccountForBilling__c</referenceTo>
    <relationshipLabel>Facturas Vista 360</relationshipLabel>
    <relationshipName>Facturas_Vista_360</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ContractAccountForBilling__c/OSFMX_ContractAccountForBilling__c.object-meta.xml
<CustomObject>
    <description>Almacena temporalmente cabeceras de la consulta de facturación hacía Denodo y Global Hitss, para mostrar en la vista 360. Debe ser borrada cada noche.</description>
    <label>Cuenta Contrato Para Facturacion</label>
    <nameField>
        <label>Business Partner</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas Contrato Para Facturacion</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_sfdx/main/default/objects/OSFMX_ContractAccountForBilling__c/fields/OSFMX_CuentaContrato__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_CuentaContrato__c</fullName>
    <externalId>true</externalId>
    <label>Cuenta Contrato</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce_sfdx/main/default/classes/OSFMX_DeleteInvoiceSchedulable_test.cls
/***********************************************************************************
    Developed by:   Roberto Rodriguez Anaya
    Author      :   Roberto Rodriguez Anaya
    Project     :   OSFMX
    Description :   Prueba unitaria de la clase OSFMX_DeleteInvoiceSchedulable
   ================================================================================
    No.     Date                 Author                    Description      Comment
    1.0     21-Feb-2021          Roberto Rodriguez Anaya   Creation         ........


************************************************************************************/
@isTest
public class OSFMX_DeleteInvoiceSchedulable_test {
	// Dummy CRON expression: midnight on March 15.
    // Because this is a test, job executes
    // immediately after Test.stopTest().
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    
    static testmethod void testScheduledJob() {
        OSFMX_ContractAccountForBilling__c contrAcc = new OSFMX_ContractAccountForBilling__c(OSFMX_CuentaContrato__c='1234567890');
        INSERT contrAcc;
		OSFMX_360ViewInvoice__c invoiceItem = new OSFMX_360ViewInvoice__c(OSFMX_ContractAccountForBilling__c=contrAcc.Id);
        INSERT invoiceItem;
        
        Test.startTest();
        // Schedule the test job
        String jobId = System.schedule('OSFMX_DeleteInvoiceSchedulable',
                                       CRON_EXP, 
                                       new OSFMX_DeleteInvoiceSchedulable());
        // Stopping the test will run the job synchronously
        Test.stopTest();
        
        // check that the scheduled job has executed
        CronTrigger cron = 
            [
                SELECT Id,CronJobDetail.Name,State,TimesTriggered,NextFireTime 
                FROM CronTrigger
                ORDER BY CreatedDate
                DESC LIMIT 1
            ];
        System.debug('##### OSFMX_DeleteInvoiceSchedulable - cron: ' + cron);
        System.assertEquals('OSFMX_DeleteInvoiceSchedulable', 
                            cron.CronJobDetail.Name, 
                            'La clase Apex no fué programada correctamente.');
    }
}