salesforce_sfdx/main/default/objects/OSFMX_360ViewInvoice__c/OSFMX_360ViewInvoice__c.object-meta.xml
<CustomObject>
    <description>Almacena temporalmente registros de la consulta de facturación hacía Denodo y Global Hitss, para mostrar en la vista 360. Debe ser borrada cada noche.</description>
    <label>Factura Vista 360</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas Vista 360</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce_sfdx/main/default/objects/OSFMX_360ViewInvoice__c/fields/OSFMX_ContractAccountForBilling__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_ContractAccountForBilling__c</fullName>
    <label>Cuenta Contrato Para Facturacion</label>
    <referenceTo>OSFMX_ContractAccountForBilling__c</referenceTo>
    <relationshipLabel>Facturas Vista 360</relationshipLabel>
    <relationshipName>Facturas_Vista_360</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_360ViewInvoice__c/fields/OSFMX_NumFactura__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_NumFactura__c</fullName>
    <label>Numero de Factura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/OSFMX_ContractAccountForBilling__c/OSFMX_ContractAccountForBilling__c.object-meta.xml
<CustomObject>
    <description>Almacena temporalmente cabeceras de la consulta de facturación hacía Denodo y Global Hitss, para mostrar en la vista 360. Debe ser borrada cada noche.</description>
    <label>Cuenta Contrato Para Facturacion</label>
    <nameField>
        <label>Business Partner</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cuentas Contrato Para Facturacion</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_sfdx/main/default/objects/OSFMX_ContractAccountForBilling__c/fields/OSFMX_CuentaContrato__c.field-meta.xml
<CustomField>
    <fullName>OSFMX_CuentaContrato__c</fullName>
    <externalId>true</externalId>
    <label>Cuenta Contrato</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce_sfdx/main/default/classes/OSFMX_DeleteInvoiceBatch_test.cls
/***********************************************************************************
    Developed by:   Roberto Rodriguez Anaya
    Author      :   Roberto Rodriguez Anaya
    Project     :   OSFMX
    Description :   Clase Test OSFMX_DeleteInvoiceBatch_test

   ================================================================================
    No.     Date                 Author                    Description      Comment
    1.0     21-Feb-2021          Roberto Rodriguez Anaya   Creation         ........


************************************************************************************/
@isTest
public class OSFMX_DeleteInvoiceBatch_test {
    static testmethod void testExecuteBatch() {
        OSFMX_ContractAccountForBilling__c contrAcc = new OSFMX_ContractAccountForBilling__c(OSFMX_CuentaContrato__c='1234567890');
        INSERT contrAcc;
		OSFMX_360ViewInvoice__c invoiceItem = new OSFMX_360ViewInvoice__c(OSFMX_ContractAccountForBilling__c=contrAcc.Id);
        INSERT invoiceItem;
                
        Test.startTest();
        OSFMX_DeleteInvoiceBatch batch = new OSFMX_DeleteInvoiceBatch();
        Id batchId = Database.executeBatch(batch);
        Test.stopTest();
        
        // check that the scheduled job has executed
        List<OSFMX_360ViewInvoice__c> invoiceList = [SELECT Id,OSFMX_NumFactura__c FROM OSFMX_360ViewInvoice__c];
        List<OSFMX_ContractAccountForBilling__c> cAccList = [SELECT Id,OSFMX_CuentaContrato__c FROM OSFMX_ContractAccountForBilling__c];
        System.assertEquals(0, invoiceList.size(), 'Los registrso de OSFMX_360ViewInvoice__c no fueron eliminados');
        System.assertEquals(0, cAccList.size(), 'Los registrso de OSFMX_ContractAccountForBilling__c no fueron eliminados');
    }
}